spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/estudos
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
